//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Orar
{
    using System;
    using System.Collections.Generic;
    
    public  class Orar
    {
        private int codOrar;
        private string sapt;
        private string zi;
        private int codModul;
        private int codProiect;
        private int codSeminar;
        private int codTip;
        private int formatieStudiu;
    
        

        public int CodOrar
        {
            get { return codOrar; }
            set { codOrar = value; }
        }
        public string Sapt
        {
            get { return sapt; }
            set { sapt = value; }
        }
        public string Zi
        {
            get { return zi; }
            set { zi = value; }
        }
        public int CodModul
        {
            get { return codModul; }
            set { codModul = value; }
        }
        public int CodProiect
        {
            get { return codProiect; }
            set { codProiect = value; }
        }
        public int CodSemianr
        {
            get { return codSeminar; }
            set { codSeminar = value; }
        }
       
        public int CodTip
        {
            get { return codTip; }
            set { codTip = value; }
        }
        public int FormatieStudiu
        {
            get { return formatieStudiu; }
            set { formatieStudiu = value; }
        }

        public void Insert(int codOrar, String sapt, String zi, int codModul, int codSeminar, int codTip, int formatieStudiu)
        {

        }
        public void Update()
        {

        }
        public void Delete()
        {

        }




    }
}
